---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- templates/
